# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-03 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecategory',
            table='ArticleCategory',
        ),
        migrations.AlterModelTable(
            name='articles',
            table='Articles',
        ),
        migrations.AlterModelTable(
            name='authors',
            table='Authors',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='Comments',
        ),
    ]
