# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-03 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180603_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name_plural': 'ArticleCategories'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='pulished_at',
            new_name='pulished_date',
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='author',
            table='Author',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
