# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-03 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180603_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'blog_articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name_plural': 'blog_ArticleCategories'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'blog_authors'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'blog_comments'},
        ),
    ]
