# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180603_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
