# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-03 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pulished_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 3, 15, 38, 4, 929000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
