# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-05 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180604_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('view_category', 'View category'),)},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
