# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-08 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180605_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='forbbiden_comment',
            field=models.BooleanField(default=1, verbose_name='\u7981\u6b62\u8bc4\u8bba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=1, verbose_name='\u516c\u5f00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=0, verbose_name='\u7f6e\u9876'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pulished_date',
            field=models.DateField(verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='\u6587\u7ae0\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u540d\u5b57'),
        ),
    ]
