# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-08 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180608_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u6587\u7ae0\u6458\u8981'),
        ),
    ]
