# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-08 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='forbbiden_comment',
        ),
        migrations.AddField(
            model_name='article',
            name='is_forbbiden_comment',
            field=models.BooleanField(default=0, verbose_name='\u7981\u6b62\u8bc4\u8bba'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='\u6587\u7ae0\u6458\u8981'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=1, verbose_name='\u516c\u5f00'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=0, verbose_name='\u7f6e\u9876'),
        ),
    ]
