# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-09 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180608_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.IntegerField(default=1, verbose_name='\u6587\u7ae0\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
