# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-09 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.IntegerField(default=1, verbose_name='\u6587\u7ae0\u7c7b\u578b'),
        ),
    ]
