# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-09 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pulished_date',
            new_name='published_date',
        ),
    ]
