# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180609_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pulished_date',
            field=models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
