# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
