# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-10 16:07
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180610_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('picture', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
