# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-12 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0033_auto_20180613_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='article',
            new_name='like_article',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='comment',
            new_name='like_comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='like_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
