# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-12 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20180613_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_article',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_comment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
