# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-13 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20180613_2025'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='blog_Tag',
        ),
    ]
