# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-13 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20180613_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='\u540d\u5b57'),
        ),
    ]
