# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-17 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20180618_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite_article',
            new_name='article',
        ),
    ]
