# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-21 04:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0045_messages_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='to_user',
        ),
        migrations.AddField(
            model_name='messages',
            name='receive_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_receive_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='send_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_send_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
