# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20180621_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=0),
        ),
    ]
