# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20180621_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
