# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-28 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0050_auto_20180626_1240'),
    ]

    operations = [

    ]
