# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-29 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0051_auto_20180628_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
