# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20180629_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcategory',
            name='default',
            field=models.IntegerField(default=0),
        ),
    ]
