# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-28 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0050_auto_20180626_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_CustomCategory',
                'verbose_name_plural': 'CustomCategory',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='custom_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.CustomCategory'),
            preserve_default=False,
        ),
    ]
