# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_auto_20180628_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(default=0, verbose_name='\u5220\u9664'),
        ),
    ]
