# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-22 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20180522_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=3, unique=True),
            preserve_default=False,
        ),
    ]
